Users can now provision using a service principal.
scobb/azure-cli pull request #18
Opened 2017-04-28 21:09 UTC by scobb

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [ ] Each command and parameter has a meaningful description.
- [ ] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

2017-04-28 22:05 UTC, tudordid commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_az_util.py
> +    :param service_principal: str name of service principal
nit: define these in order

2017-04-28 22:08 UTC, tudordid approved these changes

2017-04-28 22:32 UTC, Chris113113 requested changes

2017-04-28 22:32 UTC, Chris113113 commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_az_util.py
> +            return True
Are we using these return values anywhere?

2017-04-28 22:32 UTC, Chris113113 commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_params.py
> +register_cli_argument('ml env setup', 'tenant', options_list=('-t', '--tenant'), help='Tenant associated with service principal.', required=False)
Change these to match the output of 'az ad sp create-for-rbac'. This is a little confusing.

2017-04-28 22:32 UTC, Chris113113 commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_az_util.py
> +    print(client_secret)
Are these debug?

2017-04-28 23:31 UTC, scobb commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_params.py
> +register_cli_argument('ml env setup', 'tenant', options_list=('-t', '--tenant'), help='Tenant associated with service principal.', required=False)
They currently match the inputs to `az acs create.` Maybe I can add to the help message?

2017-05-01 17:59 UTC, scobb commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_az_util.py
> +            return True
Nope. Will remove.

2017-05-01 18:58 UTC, Chris113113 approved these changes

2017-05-02 20:44 UTC, ritwik20 approved these changes

2017-05-02 20:44 UTC, ritwik20 commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_acs_util.py
> +    except Exception:  # pylint: disable=bare-except
Remove the pylint directive, since it's not a bare exception any more?

2017-05-02 20:44 UTC, ritwik20 commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_az_util.py
> +            profile.find_subscriptions_on_login(False, service_principal, client_secret, True, tenant)
This will end up creating resources on behalf of the SP, not the user that is running the CLI. It might mean that default ACL'ing of these resources by ARM will be to the SP, which might not be what the user intended. Why log them in with the SP?

2017-05-02 20:44 UTC, ritwik20 commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_acs_util.py
>              'Failed to validate service principal, if this persists try deleting $HOME/.azure/acsServicePrincipal.json')
Can we put acsServicePrincipal.json in the RealTimeConstants class, instead of hard-coding in multiple places?

2017-05-02 20:44 UTC, ritwik20 commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/env.py
> +    az_login()
Any specific reason to remove the try...except block around this?

2017-05-02 20:44 UTC, ritwik20 commented on src/command_modules/azure-cli-ml/setup.py
> +    'adal',
>=?

2017-05-02 22:46 UTC, scobb commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/_acs_util.py
>              'Failed to validate service principal, if this persists try deleting $HOME/.azure/acsServicePrincipal.json')
RealtimeConstants makes for difficulty with imports (plus it's an env thing, more than realtime). I added it to _acs_util as a constant.

2017-05-02 22:56 UTC, scobb commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/env.py
> +    az_login()
None of the functions raise an AzureCliError. I have updated the AzureCliError raised at line 411 to be a CLIError, which is handled by azure-cli main.

2017-05-02 23:05 UTC, merged