Removing logging level from cli
scobb/azure-cli pull request #21
Opened 2017-05-01 22:48 UTC by adamblev

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [ ] Each command and parameter has a meaningful description.
- [ ] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

2017-05-01 23:20 UTC, Chris113113 approved these changes
Since we've removed specified logging levels, are we going to be logging equivalent to Debug now?

2017-05-01 23:24 UTC, jajan17 commented
The logging levels were a workaround to preserve logs on the console output since the hooks intercept stdout/stderr. They don't actually control the level of verbosity for logs that go to app insights. It impacts the logging level that you see in the console and they've been changed to what it was before (info).

2017-05-01 23:28 UTC, scobb commented
Apologies about the CI spam. I was just seeing how TravisCI works. Can ignore.

2017-05-02 18:06 UTC, scobb requested changes
nit on boolean -> string conversion

2017-05-02 18:06 UTC, scobb commented on src/command_modules/azure-cli-ml/azure/cli/command_modules/ml/service/realtime.py
> +    if app_insights_logging_enabled:
app_insights_enabled = str(app_insights_logging_enabled).lower()

2017-05-02 22:20 UTC, scobb approved these changes

2017-05-02 22:22 UTC, merged